// Generated by CoffeeScript 1.9.1
(function() {
  var container, resize, slider;

  container = 1200;

  $(document).ready(function() {
    var menuToggle;
    resize();
    menuToggle = $("#js-mobile-menu").unbind();
    $("#js-navigation-menu").removeClass("show");
    menuToggle.on("click", function(e) {
      e.preventDefault();
      $("#js-navigation-menu").slideToggle(function() {
        if ($("#js-navigation-menu").is(":hidden")) {
          $("#js-navigation-menu").removeAttr("style");
        }
      });
    });
    $(document).on('init.slides', function() {
      return $('.loading-container').fadeOut(function() {
        $(this).remove();
      });
    });
    $('#slides').hammer().on('swipeleft', function() {
      return $(this).superslides('animate', 'next');
    });
    $('#slides').hammer().on('swiperight', function() {
      return $(this).superslides('animate', 'prev');
    });
    $(window).on({
      'resize': function() {
        return resize();
      }
    });
    setTimeout(slider, 500);
  });

  resize = function() {
    var ancho;
    ancho = $(window).width();
    return $('.js-bg-left').width((ancho - container) / 2);
  };

  slider = function() {
    $('#slides').superslides({
      pagination: false,
      animation: 'fade'
    });
    return $('.slides-container, .slides-navigation').fadeIn();
  };

}).call(this);
