// Generated by CoffeeScript 1.9.1
(function() {
  $(document).ready(function() {
    var menuToggle;
    menuToggle = $("#js-mobile-menu").unbind();
    $("#js-navigation-menu").removeClass("show");
    menuToggle.on("click", function(e) {
      e.preventDefault();
      $("#js-navigation-menu").slideToggle(function() {
        if ($("#js-navigation-menu").is(":hidden")) {
          $("#js-navigation-menu").removeAttr("style");
        }
      });
    });
    $(document).on('init.slides', function() {
      return $('.loading-container').fadeOut(function() {
        $(this).remove();
      });
    });
  });

}).call(this);
